import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
  },
  podiumContainer: {
    marginTop: 20,
    marginBottom: 40,
    paddingTop: 30,
    paddingBottom: 5,
    width: "88%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
    borderRadius: 10,
    marginVertical: 8,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  title: {
    color: "#aaa",
    fontFamily: 'Avenir Next Condensed',
    fontSize: 62,
    fontWeight: "bold",
    marginBottom: 30,
  },
  subtitle: {
    color: "#bbb",
    fontFamily: 'Avenir Next Condensed',
    fontSize: 28,
    fontWeight: "bold",
    marginTop: 160,
    marginBottom: -8,
  },
  stepRow: {
    backgroundColor: "#6c5ce7",
    borderRadius: 16,
    borderWidth: 4,
    borderColor: "white",
    padding: 10,
    justifyContent: "center",
    height: 90,
    width: "90%",
    marginBottom: 4,
  },
  stepText: {
    fontSize: 30,
    fontFamily: 'Avenir Next',
    fontWeight: "bold",
    color: "#fff",
  },
  pointsText: {
    position: "absolute",
    alignSelf: "center",
    fontSize: 36,
    fontFamily: 'Avenir Next',
    fontWeight: "bold",
    color: "#fff",
  },
  buttonRow: {
    position: "absolute",
    width: "90%",
    justifyContent: "space-around",
    bottom: 50,
    flexDirection: "row",
  },
  button: {
    flexDirection: "row",
    borderRadius: 16,
    height: 80,
    width: "48%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
    opacity: 0.9,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  buttonText: {
    fontSize: 24,
    fontFamily: 'Avenir Next',
    fontWeight: "bold",
    color: "#999"
  },
});