import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    scrollContainer: {
        alignItems: 'center',
        paddingBottom: 220,
        paddingHorizontal: 16,
    },
    backButton:{
        position: "absolute",
        alignSelf: "flex-start",
        backgroundColor: "white",
        borderWidth: 2,
        borderColor: '#dcdde1',
        height: 40,
        width: 40,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 50,
        top: 10,
    },
    titleContainer: {
         justifyContent: "center",
         alignItems: "center",
         position: 'relative',
         marginBottom: 260,
    },
    title: {
        position: 'absolute',
        fontWeight: 'bold',
        fontFamily: 'Avenir Next Condensed',
        color: '#6c5ce7',
        textAlign: 'center',
        width: 'auto',
    },
    wordWrapper: {
        position: 'absolute',
        width: '100%',
        alignItems: 'center',
    },
    settingsContainer: {
        width: '100%',
        alignItems: "center",
        paddingTop: 16,
        paddingBottom: 24,
        backgroundColor: 'white',
        borderRadius: 16,
        borderWidth: 2,
        borderColor: '#dcdde1',
        overflow: 'hidden',
        marginBottom: 24,
    },
    teamContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        width: '92%',
        marginBottom: 10,
    },
    teamBox: {
        width: '48%',
        marginTop: 8,
        marginBottom: 6,
        borderRadius: 15,
        padding: 10,
    },
    teamTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        left: 34,
        marginBottom: 10,
        color: 'white',
        width: '60%',
    },
    editIcon: {
        position: 'absolute',
        top: 13,
        left: 13,
        zIndex: 10
    },
    teamInput: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#fff',
        paddingHorizontal: 6,
        width: '77%',
        alignSelf: 'flex-end',
        marginBottom: 10,
    },
    playerInput: {
        backgroundColor: '#fff',
        padding: 8,
        borderRadius: 8,
        fontSize: 16,
        marginBottom: 8,
        borderWidth: 1,
        paddingHorizontal: 12,
        borderColor: '#ccc',
    },
    addPlayerText: {
        color: 'white',
        marginTop: 4,
        marginBottom: 4,
        fontSize: 12,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    addTeamText: {
        fontSize: 16,
        color: '#6c5ce7',
        textAlign: 'center',
        marginBottom: 8,
        fontWeight: 'bold',
    },
    teamResetButton: {
        position: 'absolute',
        bottom: 0,
        right: 30,
        backgroundColor: "#6c5ce7",
        width: 45,
        height: 45,
        borderRadius: 30,
        alignItems: "center",
        justifyContent: "center",
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 5,
    },
    roundRandomizer: {
        flexDirection: 'row',
        backgroundColor: '#6c5ce7',
        padding: 12,
        paddingLeft: 15,
        paddingRight: 15,
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 5,
    },
    roundRandomizerText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16
    },
    checkboxRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 6,
    },
    checkboxLabel: {
        marginLeft: 8,
        fontSize: 15,
        color: '#636e72',
    },
    startButton: {
        paddingLeft: 30,
        paddingRight: 30,
        position: 'absolute',
        alignSelf: "center",
        bottom: 40,
        paddingTop: 18,
        paddingBottom: 18,
        borderRadius: 60,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#6c5ce7',
        marginTop: 10,
        marginBottom: 60,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 5,
    },
    startButtonText: {
        fontSize: 34,
        fontWeight: '800',
        color: 'white',
    },
    explanationText: {
        fontSize: 15,
        color: '#636e72',
        textAlign: 'center',
        fontWeight: 'bold',
    }
})