import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#6c5ce7',
    paddingTop: 130,
    alignItems: 'center',
    width: "100%",
  },
  title: {
    fontSize: 90,
    fontWeight: 'bold',
    fontFamily: 'Avenir Next Condensed',
    color: 'white',
    textAlign: 'center',
    marginBottom: 10,
  },
  carouselContainer: {
    height: 336,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  box: {
    justifyContent: "center",
    backgroundColor: "white",
    borderRadius: 10,
    borderWidth: 5,
    borderColor: "white",
    padding: 15,
    marginVertical: 8,
    height: 320,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  explanationBox:{
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    backgroundColor: "white",
    opacity: 0.9,
    borderRadius: 50,
    width: 38,
    height: 38,
    bottom: 28,
    right: 32,
  },
  boxText: {
    position: "absolute",
    fontSize: 20,
    fontWeight: "600",
    top: 40,
    fontFamily: "Avenir Next",
    color: "white",
    alignSelf: "center",
  },
  boxExplanationText: {
    fontSize: 32,
    fontWeight: "bold",
    fontFamily: "Avenir Next",
    color: "white",
    textAlign: "left",
    left: 20,
  },
  boxTitle: {
    fontSize: 66,
    textAlign: "center",
    color: "white",
    fontFamily: "Avenir Next",
    fontWeight: "bold",
    alignSelf: "center",
    marginBottom: 0,
  },
  eighteenPlusSign:{
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#a29bfe",
    transform: [{rotate: "6deg"}],
    bottom: 120,
    right: 1,
    height: 70,
    width: 110,
    borderWidth: 8,
    borderRadius: 20,
    borderColor: "#6c5ce7"
  },
  eighteenPlusText:{
    fontSize: 36,
    color: "#fff",
    fontWeight: "800",
    fontFamily: "Avenir Next Condensed"
  },
  arrow: {
    position: "absolute",
    height: 180,
    width: 90,
    justifyContent: "center",
  },
  arrowLeft: {
    alignItems: "flex-start",
    left: 10,
  },
  arrowRight: {
    alignItems: "flex-end",
    right: 10,
  },
  footer: {
    marginTop: 50,
    alignItems: "center",
  },
  subtitle:{
    fontSize: 20,
    marginTop: 10,
    fontWeight: 'bold',
    fontFamily: 'Avenir Next',
    color: 'white',
    textAlign: 'center',
  },
  startButton: {
    backgroundColor: 'white',
    borderRadius: 14,
    borderColor: "white",
    borderWidth: 3,
    width: "88%",
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  startButtonText: {
    fontSize: 38,
    fontWeight: 'bold',
    fontFamily: 'Avenir Next',
    color: 'white',
    alignItems: 'center',
  },
});