import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        alignItems: "center",
        justifyContent: 'center',
    },
    exitButton:{
        position: "absolute",
        alignSelf: "flex-start",
        backgroundColor: "white",
        borderColor: '#dcdde1',
        height: 30,
        width: 30,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 50,
        opacity: 0.6,
    },
    subtitle: {
        fontSize: 34,
        marginTop: 70,
        fontWeight: 'bold',
        fontFamily: 'Avenir Next',
        textAlign: "center",
        marginBottom: 20,
        color: "white",
    },
    title: {
        color: "black",
        fontFamily: 'Avenir Next Condensed',
        fontWeight: "bold",
        marginBottom: 10,
        top: 30,
        textAlign: "center",
    },
    nameBox: {
        alignItems: "center",
        backgroundColor: "white",
        borderRadius: 10,
        marginTop: 0,
        marginBottom: 50,
        width: "88%",
        height: 500,
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
        elevation: 3,
    },
    textBox: {
        position: "absolute",
        justifyContent: "center",
        alignItems: "center",
        top: 0,
        height: 170,
        width: "100%",
    },
    startButton: {
        width: '50%',
        alignSelf: "center",
        paddingTop: 18,
        paddingBottom: 18,
        borderRadius: 60,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'white',
        marginBottom: 60,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 5,
    },
    startButtonText: {
        fontSize: 34,
        fontWeight: '800',
        color: 'black',
    },
})