import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    alignItems: "center",
    paddingBottom: 100,
  },
  exitButton:{
    position: "absolute",
    alignSelf: "flex-start",
    backgroundColor: "white",
    borderColor: '#dcdde1',
    height: 30,
    width: 30,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 50,
    opacity: 0.6,
  },
  subtitle: {
    fontSize: 22,
    marginTop: 120,
    marginBottom: 5,
    textAlign: "center",
    color: "#555",
  },
  title: {
    fontSize: 56,
    fontWeight: "bold",
    marginBottom: 30,
    textAlign: "center",
    color: "#555",
  },
  box: {
    backgroundColor: "white",
    borderRadius: 10,
    paddingTop: 12,
    paddingBottom: 22,
    paddingHorizontal: 24,
    marginVertical: 8,
    borderWidth: 3,
    width: "86%",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  boxTitle: {
    fontSize: 26,
    fontWeight: "bold",
    marginBottom: 8,
    textAlign: "center",
    fontFamily: 'Avenir Next',
    color: "#636e72",
  },
  boxText: {
    fontSize: 17,
    textAlign: "left",
    fontFamily: 'Avenir Next',
    color: "#636e72",
  },
  button: {
    paddingLeft: 30,
    paddingRight: 30,
    paddingTop: 18,
    paddingBottom: 18,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    width: "60%",
    marginTop: 40,
    marginBottom: 0,
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 50,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  buttonText: {
    color: "white",
    fontSize: 28,
    fontWeight: "bold",
    textAlign: "center",
  },
});
