import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    scrollContainer: {
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingBottom: 220,
    },
    backButton:{
        position: "absolute",
        alignSelf: "flex-start",
        backgroundColor: "white",
        borderWidth: 2,
        borderColor: '#dcdde1',
        height: 40,
        width: 40,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 50,
        top: 10,
    },
    titleContainer: {
         justifyContent: "center",
         alignItems: "center",
         position: 'relative',
         marginBottom: 280,
    },
    title: {
        position: 'absolute',
        fontWeight: 'bold',
        fontFamily: 'Avenir Next Condensed',
        color: '#6c5ce7',
        textAlign: 'center',
        width: 'auto',
    },
    wordWrapper: {
        position: 'absolute',
        width: '100%',
        alignItems: 'center',
    },
    startButton: {
        paddingLeft: 30,
        paddingRight: 30,
        position: 'absolute',
        alignSelf: "center",
        bottom: 40,
        paddingTop: 18,
        paddingBottom: 18,
        borderRadius: 60,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#6c5ce7',
        marginTop: 10,
        marginBottom: 60,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 5,
    },
    startButtonText: {
        fontSize: 34,
        fontWeight: '800',
        color: 'white',
    },
    accordionContainer: {
        width: '100%',
        backgroundColor: '#ffffff',
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#dcdde1',
        overflow: 'hidden',
        marginBottom: 24,
    },
    accordionHeader: {
        paddingVertical: 16,
        paddingHorizontal: 20,
        borderBottomWidth: 2,
        borderBottomColor: '#dcdde1',
        backgroundColor: '#ffffff',
    },
    accordionContent: {
        padding: 10,
        backgroundColor: '#f9f9f9',
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: '800',
        textAlign: 'center',
        color: '#636e72',
    },
    teamContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        width: '100%',
        marginBottom: 10,
    },
    teamBox: {
        width: '48%',
        marginTop: 8,
        marginBottom: 6,
        borderRadius: 15,
        padding: 10,
    },
    teamTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        left: 34,
        marginBottom: 10,
        color: 'white',
        width: '60%',
    },
    editIcon: {
        position: 'absolute',
        top: 13,
        left: 13,
        zIndex: 10
    },
    teamInput: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#fff',
        paddingHorizontal: 6,
        width: '77%',
        alignSelf: 'flex-end',
        marginBottom: 10,
    },
    playerInput: {
        backgroundColor: '#fff',
        padding: 8,
        borderRadius: 8,
        fontSize: 16,
        marginBottom: 8,
        borderWidth: 1,
        paddingHorizontal: 12,
        borderColor: '#ccc',
    },
    addPlayerText: {
        color: 'white',
        marginTop: 4,
        marginBottom: 4,
        fontSize: 12,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    addTeamText: {
        fontSize: 16,
        color: '#6c5ce7',
        textAlign: 'center',
        marginBottom: 8,
        fontWeight: 'bold',
    },
    teamResetButton: {
        position: 'absolute',
            bottom: 20,
            right: 40,
            backgroundColor: "#6c5ce7",
            width: 45,
            height: 45,
            borderRadius: 30,
            alignItems: "center",
            justifyContent: "center",
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.2,
            shadowRadius: 6,
            elevation: 5,
    },
    difficultySliderContainer: {
        width: '100%',
        padding: 16,
        borderRadius: 12,
        backgroundColor: '#f1f2f6',
        marginTop: 10,
        marginBottom: 8,
    },
    difficultyHeader: {
        fontSize: 18,
        color: '#636e72',
        textAlign: 'center',
        fontWeight: 'bold',
        marginBottom: 6,
    },
    difficultyLabelsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 5,
    },
    difficultyLabelSmall: {
        fontSize: 14,
        color: '#636e72',
    },
    timeSliderContainer: {
        width: '100%',
        padding: 16,
        borderRadius: 12,
        backgroundColor: '#f1f2f6',
        marginTop: 10,
        marginBottom: 10,
    },
    timeLimitLabel: {
        fontSize: 14,
        color: '#636e72',
        textAlign: 'center',
    },
    categoriesWrapper: {
        width: '100%',
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    categoriesHeader: {
        fontSize: 18,
        color: '#636e72',
        textAlign: 'center',
        fontWeight: 'bold',
        marginTop: 10,
        marginBottom: 10,
    },
    categoryBox: {
        width: '30%',
        marginVertical: 7,
        marginHorizontal: '1.5%',
        padding: 12,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 116,
    },
    categoryText: {
        color: 'white',
        fontWeight: 'bold',
        textAlign: 'center',
        fontSize: 15,
        fontFamily: 'Avenir Next Condensed'
    },
    roundsContainer: {
        width: '100%',
        marginBottom: 20,
    },
    roundsLabel: {
        textAlign: 'center',
        fontSize: 14,
        fontWeight: 'bold',
        color: '#636e72',
        marginTop: 10,
        marginBottom: 10,
    },
    roundLabelSmall: {
        fontSize: 20,
        paddingLeft: 16,
        color: 'white',
        fontFamily: 'Avenir Next',
        fontWeight: 'bold',
    },
    roundRandomizer: {
        flexDirection: 'row',
        backgroundColor: '#6c5ce7',
        padding: 12,
        marginBottom: 10,
        paddingLeft: 15,
        paddingRight: 15,
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 5,
    },
    roundRandomizerText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16
    },
    checkboxRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 6,
    },
    checkboxLabel: {
        marginLeft: 8,
        fontSize: 15,
        color: '#636e72',
    },
    explanationText: {
        fontSize: 15,
        color: '#636e72',
        textAlign: 'center',
        fontWeight: 'bold',
    }
});