import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center"
  },
  exitButton:{
    position: "absolute",
    alignSelf: "flex-start",
    backgroundColor: "white",
    borderColor: '#dcdde1',
    height: 30,
    width: 30,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 50,
    opacity: 0.6,
  },
  subtitle: {
    fontSize: 23,
    bottom: 1,
    left: -30,
    fontWeight: "bold",
    fontFamily: "Avenir Next",
    textAlign: "center",
    color: "white",
    opacity: 0.8,
  },
  title: {
    fontSize: 90,
    textAlign: "center",
    fontWeight: "bold",
    fontFamily: "Avenir Next Condensed",
    color: "white",
    maxWidth: "70%",
  },
  carouselContainer: {
    height: 336,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  box: {
    justifyContent: "center",
    backgroundColor: "white",
    borderRadius: 10,
    borderWidth: 5,
    borderColor: "white",
    padding: 15,
    height: 320,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
    },
  boxTitle: {
    position: "absolute",
    fontSize: 20,
    fontWeight: "600",
    top: 40,
    fontFamily: "Avenir Next",
    color: "white",
    alignSelf: "center",
  },
  boxText: {
    fontSize: 60,
    textAlign: "center",
    color: "white",
    fontFamily: "Avenir Next",
    fontWeight: "bold",
    maxWidth: "85%",
    alignSelf: "center",
  },
  boxTextBelow: {
    position: "absolute",
    fontSize: 24,
    fontWeight: "600",
    bottom: 32,
    fontFamily: "Avenir Next",
    color: "white",
    alignSelf: "center",
  },
  explanationText:{
    position: "absolute",
    textAlign: "center",
    fontSize: 26,
    backgroundColor: "#6c5ce7",
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 8,
    fontWeight: "bold",
    fontFamily: "Avenir Next",
    color: "white",
  },
  arrow: {
    position: "absolute",
    marginBottom: 40,
    height: 140,
    paddingTop: 22,
    width: 110,
    justifyContent: "center",
  },
  arrowLeft: {
    alignItems: "flex-start",
    left: 10,
  },
  arrowRight: {
    alignItems: "flex-end",
    right: 10,
  },
  footer: {
    marginTop: 20,
    alignItems: "center",
  },
  startButton: {
    alignSelf: "center",
    width: 130,
    height: 130,
    borderRadius: 100,
    justifyContent: "center",
    backgroundColor: "white",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  jokerButton:{
    position: "absolute",
    alignItems: "center",
    bottom: 14, 
    left: 176,
  },
  jokerText:{
    fontSize: 26,
    color: "white",
    fontWeight: "800",
    marginTop: 4,
  },
  redMarkButton: {
    position: "absolute",
    bottom: 4,
    left: 4,
    paddingLeft: 30,
    paddingBottom: 20,
    width: 120,
    height: 120,
    borderRadius: 20,
    justifyContent: "flex-end",
    alignItems: "flex-start",
  },
  greenMarkButton: {
    position: "absolute",
    bottom: 4,
    right: 4,
    paddingRight: 30,
    paddingBottom: 20,
    width: 120,
    height: 120,
    borderRadius: 20,
    justifyContent: "flex-end",
    alignItems: "flex-end",
  },
});

